workflows:
  # Android Release Build
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true

  # iOS App Store Release
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Lume AI Key
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.yuna.yoga.bauti"
    scripts:
      - name: Setup signing, build, and export
        script: |
          # 1. Generate RSA 2048 private key
          openssl genrsa -out /tmp/cert_key.pem 2048
          export CERTIFICATE_PRIVATE_KEY="$(cat /tmp/cert_key.pem)"
          echo "=== Private key generated ==="
          
          # 2. Fetch signing files (creates new certificate + provisioning profile)
          app-store-connect fetch-signing-files com.yuna.yoga.bauti \
            --type IOS_APP_STORE \
            --create
          echo "=== Signing files fetched ==="
          
          # 3. Debug: show installed code signing identities
          echo "=== Keychain certificates ==="
          security find-identity -v -p codesigning
          
          # 4. Apply profiles to Xcode project (switches to manual signing)
          xcode-project use-profiles
          echo "=== Profiles applied ==="
          
          # 5. Show export options
          echo "=== Export options plist ==="
          cat /Users/builder/export_options.plist || echo "No export options plist found"
          
          # 6. Get Flutter dependencies
          flutter packages pub get
          
          # 7. Install pods
          cd ios && pod install && cd ..
          
          # 8. Build IPA
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
          
          # 9. Find IPA
          echo "=== Looking for IPA ==="
          find build -name "*.ipa" 2>/dev/null
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
