workflows:
  # Android Release Build
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true

  # iOS App Store Release
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Lume AI Key
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.yuna.yoga.bauti"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yuna.yoga.bauti
    scripts:
      - name: Setup signing, build, and export
        script: |
          # 1. Generate RSA 2048 private key
          openssl genrsa -out /tmp/cert_key.pem 2048
          echo "Private key generated"
          
          # 2. Set env var in current shell (not CM_ENV, to keep in same process)
          export CERTIFICATE_PRIVATE_KEY="$(cat /tmp/cert_key.pem)"
          
          # 3. Fetch signing files (certificate + provisioning profile)
          app-store-connect fetch-signing-files com.yuna.yoga.bauti \
            --type IOS_APP_STORE \
            --create
          echo "Signing files fetched"
          
          # 4. Debug: show what certificates are installed
          security find-identity -v -p codesigning
          
          # 5. Apply profiles to Xcode project
          xcode-project use-profiles
          echo "Profiles applied"
          
          # 6. Show export options plist content
          echo "Export options:"
          cat /Users/builder/export_options.plist
          
          # 7. Get Flutter dependencies
          flutter packages pub get
          
          # 8. Install pods
          cd ios && pod install && cd ..
          
          # 9. Build IPA
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
          
          # 10. Find IPA
          echo "Looking for IPA:"
          find build -name "*.ipa" 2>/dev/null
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
