workflows:
  # Android Release Build
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      groups:
        - revenuecat
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true

  # iOS App Store Release
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Lume AI Key # Switching to a key with verified Admin access
    environment:
      flutter: stable
      xcode: latest
      groups:
        - revenuecat # Removed app_store_credentials to avoid conflicts with manual profiles
      vars:
        BUNDLE_ID: "com.yuna.yoga.bauti"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yuna.yoga.bauti
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          # Flutter will use certificates auto-generated by Codemagic via App Store Connect API
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        # Submit to TestFlight
        submit_to_testflight: true
        # Uncomment to auto-submit to App Store review
        # submit_to_app_store: true
