workflows:
  # Android Release Build
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      groups:
        - revenuecat
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true

  # iOS App Store Release
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Lume AI Key
    environment:
      flutter: stable
      xcode: latest
      groups:
        - revenuecat
      vars:
        BUNDLE_ID: "com.yuna.yoga.bauti"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yuna.yoga.bauti
    scripts:
      - name: Generate certificate key and fetch signing files
        script: |
          # Generate EC P-256 private key for the signing certificate
          openssl ecparam -genkey -name prime256v1 -noout -out /tmp/cert_key.pem
          echo "EC private key generated"
          cat /tmp/cert_key.pem | head -1
          
          # Set the env var that Codemagic CLI uses internally
          export CM_CERTIFICATE_PRIVATE_KEY="$(cat /tmp/cert_key.pem)"
          
          # Now fetch-signing-files will use CM_CERTIFICATE_PRIVATE_KEY automatically
          app-store-connect fetch-signing-files com.yuna.yoga.bauti \
            --type IOS_APP_STORE \
            --create
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
