workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      groups:
        - revenuecat # Optional: if you add environment variables there
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - bauti@example.com # Change this to your email
        notify:
          success: true
          failure: true
