workflows:
  # Android Release Build
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true

  # iOS App Store Release
  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Lume AI Key
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up code signing
        script: |
          set -e

          # Generate RSA 2048 private key (required by Apple)
          openssl genrsa -out /tmp/cert_key.pem 2048
          echo "✓ RSA key generated"

          # Fetch or create signing files from App Store Connect
          app-store-connect fetch-signing-files com.yuna.yoga.bauti \
            --type IOS_APP_STORE \
            --certificate-key /tmp/cert_key.pem \
            --create
          echo "✓ Signing files fetched"

          echo "=== Installed profiles ==="
          ls ~/Library/MobileDevice/Provisioning\ Profiles/ 2>/dev/null || echo "NONE"

          # Install certificates into the keychain
          keychain add-certificates
          echo "✓ Certificates added to keychain"

          echo "=== Code signing identities ==="
          security find-identity -v -p codesigning || true

          # Configure Xcode project to use the profiles
          xcode-project use-profiles
          echo "✓ Profiles applied to Xcode project"

          echo "=== Export options plist ==="
          cat /Users/builder/export_options.plist || echo "NOT FOUND"

      - name: Get Flutter dependencies
        script: |
          flutter packages pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - bagasystudio@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
